[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "axtools"
version = "1.0.0"
dependencies = [
    "axinite",
    "vpython"
]
authors = [{ name = "Jewels", email = "jewels286@proton.me" }]
